/****** Object:  Table [dbo].[QNN_DPLY_MSG_FORSTATUS]    Script Date: 16/7/2021 1:38:25 pm ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QNN_DPLY_MSG_FORSTATUS](
	[Id] [uniqueidentifier] NOT NULL,
	[DplyMsgId] [uniqueidentifier] NOT NULL,
	[ForStatus] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_QNN_DPLY_MSG_FORSTATUS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[QNN_DPLY_MSG_FORSTATUS]  WITH CHECK ADD  CONSTRAINT [FK_QNN_DPLY_MSG_FORSTATUS_DplyId] FOREIGN KEY([DplyMsgId])
REFERENCES [dbo].[QNN_DPLY_MSG] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[QNN_DPLY_MSG_FORSTATUS] CHECK CONSTRAINT [FK_QNN_DPLY_MSG_FORSTATUS_DplyId]
GO

ALTER TABLE [dbo].[QNN_DPLY_MSG_FORSTATUS]  WITH CHECK ADD  CONSTRAINT [FK_QNN_DPLY_MSG_FORSTATUS_ForStatus] FOREIGN KEY([ForStatus])
REFERENCES [dbo].[QNN_STATUS] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[QNN_DPLY_MSG_FORSTATUS] CHECK CONSTRAINT [FK_QNN_DPLY_MSG_FORSTATUS_ForStatus]
GO

INSERT INTO dbo.QNN_DPLY_MSG_FORSTATUS(Id, DplyMsgId, ForStatus)
SELECT NewID(), Id, ForStatus
FROM dbo.QNN_DPLY_MSG
WHERE ForStatus is not null;