<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<NoWarn>1701;1702;1998</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\swz.KeyUtils\swz.KeyUtils.csproj" />
		<ProjectReference Include="..\swz.SurveyPlus.Saml2\swz.SurveyPlus.Saml2.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="saml-test-idpsigning-private-key.pem">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="saml-test-idpsigning-public-key.cer">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="saml-test-spencryption-public-key.cer">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="saml-test-spverification-public-key.cer">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
