<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1998</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1998</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="WebAssets\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="WebAssets\surveyplus-utils.js" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="WebAssets\surveyplus-utils.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="WebAssets\js\surveyplus-utils.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.AspNetCore.DataProtection.SSM" Version="3.5.0" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\swz.Clover.Core\swz.Clover.Core.csproj" />
    <ProjectReference Include="..\swz.Clover.Security\swz.Clover.Security.csproj" />
  </ItemGroup>

</Project>
