var lang = {
  clearbutton: "Clear",
  uploadbutton: "Upload",
  downloadbutton: "Download",
  toolbar:{
    sepContainers: "Containers",
    container: "DIV",
    form: "Form",
    formgroup: "Form Group",
    menu: "Menu",
    workflowbar: "Workflow bar",
    customblock: "Custom block",
    sepCollection: "Collections",
    gridview: "GridView",
    collectioneditor: "Collection Editor",
    sepControls: "Controls",
    header: "Header",
    input: "Input",
    textarea: "TextArea",
    dictionary: "Dictionary",
    dropdown: "Dropdown",
    checkbox: "CheckBox",
    radiogroup: "Radio group",
    button: "Button",
    label: "Label",
    message: "Message",
    image: "Image",
    statistic: "Statistic",
    customcontrol: "Custom control",
    staticcontent: "Static Content",
    dropdowntrigger: "Dropdown trigger",
    sepCharts: "Charts",
    barchart: "Bar",
    linechart: "Line",
    scatterchart: "Scatter",
    doughnutchart: "Doughnut",
    piechart: "Pie",
    radarchart: "Radar"
  },
  preview: {
    dropzonetext: "DROP ZONE"
  },
  editforms: {
    base:{
      generaltab: "General",
      styletab: "Style",
      eventstab: "Events",
      othertab: "Other",
      widthfield: "Width",
      heightfield: "Height",
      margintopfield: "Margin Top",
      marginbottomfield: "Margin Bottom",
      marginleftfield: "Margin Left",
      marginrightfield: "Margin Right",
      customcssclassfield: "Custom CSS class",
      stylefield: "Style",
      hiddenfield: "Hidden",
      controlhasnoeventsmsg: "This control has no events.",
      eventsinfomsg: "These flags enable processing from this element.",

      requiredfield: "Required",
      defaultvaluefield: "Default value",
      defaultvaluefield: "Default value",
      customvalidationfield: "Custom validation",
      visibleconditionfield: "Visible condition",
      readonlyconditionfield: "ReadOnly condition",

      savebutton: "Save",
      cancelbutton: "Cancel",
      okbutton: "OK",
      closebutton: "Close",

      sizedefault: "Default",
      sizemini: "Mini",
      sizetiny: "Tiny",
      sizesmall: "Small",
      sizemedium: "Medium",
      sizelarge: "Large",
      sizebig: "Big",
      sizehuge: "Huge",
      sizemassive: "Massive",

      attachednone: "None",
      attachedtop: "Top",
      attachedbottom: "Bottom",
      attachedtopright: "Top right",
      attachedtopleft: "Top left",
      attachedbottomleft: "Bottom left",
      attachedbottomright: "Bottom right",

      labeldefault: "Default",
      labelleft: "Left",
      labelright: "Right",
      labelleftcorner: "Left corner",
      labelrightcorner: "Right corner",

      closewithoutsavequestion: "Close without save?",
      questiontitle: "Question",
      onchangetimeout : "onChange timeout"
    },
    headerform :{
      namefield: "Name",
      sizefield: "Size",
      contentfield: "Content",
      textalignfield: "Text Align",
      textalignleft: "Left",
      textaligncenter: "Center",
      textalignright: "Right",
      subheaderfield: "Subheader"
    },
    buttonform :{
      namefield: "Name",
      typefield: "Type",
      typenonefield: "None",
      typesubmitfield: "Submit",
      sizefield: "Size",
      contentfield: "Content",
      optionsfield: "Options",
      basicfield: "Basic",
      circularfield: "Circular",
      compactfield: "Compact",
      disabledfield: "Disabled",
      fluidfield: "Fluid",
      invertedfield: "Inverted",
      loadingfield: "Loading",
      primaryfield: "Primary",
      secondaryfield: "Secondary",
      togglefield: "Toggle",
      floatedfield: "Floated",
      floateddefaultfield: "Default",
      floatedleftfield: "Left",
      floatedrightfield: "Right",
    },
    labelform :{
      namefield: "Name",
      attachedfield:"Attached",
      contentfield: "Content",
      sizefield: "Size", 
      optionsfield: "Options",
      contentfield: "Content",
      basicfield: "Basic",
      circularfield: "Circular",
      cornerfield: "Corner",
      floatingfield: "Floating",
      horizontalfield: "Horizontal",
      pointingfield: "Pointing"
    },
    staticcontentform:{
      namefield: "Name",
      fontsizefield: "Font size",
      contentfield: "Content",
      allowhtmlfield: "Allow HTML"
    },
    messageform:{
      namefield: "Name",
      headerfield: "Header",
      optionsfield: "Options",
      compactfield: "Compact",
      errorfield: "Error",
      floatingfield: "Floating",
      infofield: "Info",
      negativefield: "Negative",
      positivefield: "Positive",
      successfield: "Success",
      warningfield: "Warning",
      contentfield: "Content",
      sizefield: "Size"
    },
    inputform: {
      namefield: "Name",
      labelfield:"Label",
      typefield: "Type",
      typetext: "Text",
      typenumber: "Number",
      typedate: "Date",
      typetime: "Time",
      typedatetime: "Date & Time",
      typepasswod: "Password",
      labelpositionfield: "Label position",
      optionsfield: "Options",
      loadingfield: "Loading",
      invertedfield: "Inverted",
      errorfield: "Error",
      disabledfield: "Disabled",
      transparentfield: "Transparent",
      fluidfield: "Fluid",
      readonlyfield: "Read only",
      placeholderfield: "Placeholder",
      sizefield:"Size",
      dateformatfield: "Date Format"
    },
    textareaform: {
      namefield: "Name",
      labelfield:"Label",
      rowsfield: "Rows",
      optionsfield: "Options",
      placeholderfield: "Placeholder",
      autoheightfield: "Auto height",
      readonlyfield: "Read only",
    },
    checkboxform: {
      namefield: "Name",
      labelfield:"Label",
      optionsfield: "Options",
      fittedfield: "Fitted",
      indeterminatefield: "Indeterminate",
      readonlyfield: "ReadOnly",
      disabledfield: "Disabled",
      sliderfield: "Slider",
      togglefield: "Toggle"
    },
    dropdownform: {
      namefield: "Name",
      labelfield:"Label",
      datafield: "Data",
      datakeycolumn: "Key",
      datavaluecolumn: "Value",
      datatextcolumn: "Text",
      optionsfield: "Options",
      loadingfield: "Loading",
      errorfield: "Error",
      disabledfield: "Disabled",
      fluidfield: "Fluid",
      multiplefield: "Multiple",
      searchfield: "Search",
      selectionfield: "Selection",
      readonlyfield: "Read only",
      clearablefield: "Clearable",
      allowAddItemsfield: "Allow add items"
    },
    dictionaryform: {
      namefield: "Name",
      labelfield:"Label",
      datamodelfield: "Data model",
      placeholderfield: "Placeholder",
      columnsfield: "Columns (Name ASC, Email)",
      optionsfield: "Options",
      loadingfield: "Loading",
      errorfield: "Error",
      disabledfield: "Disabled",
      fluidfield: "Fluid",
      multiplefield: "Multiple",
      searchfield: "Search",
      selectionfield: "Selection",
      readonlyfield: "Read only",
      clearablefield: "Clearable",
      pagingfield: "Server pagination",
      pagesizefield: "Page Size",
      parentidField: "Parent Field"
    },
    radiogroupform: {
      namefield: "Name",
      labelfield:"Label",
      datafield: "Data",
      datakeycolumn: "Key",
      datavaluecolumn: "Value",
      datatextcolumn: "Text",
      groupdirectfield: "Group direct",
      directiongorizontalfield: "Horizontal",
      directionverticalfield: "Vertical",
      readonlyfield: "Read only"
    },
    form: {
      namefield: "Name",
      sizefield: "Size",
      optionsfield: "Options",
      loadingfield: "Loading",
      errorfield: "Error",
      invertedfield: "Inverted",
      replyfield: "Reply",
      successfield: "Success",
      warningfield: "Warning"
    },
    formgroupform: {
      namefield: "Name",
      widthsfield: "Widths",
      widthsdefaultfield: "Default",
      widthsequalfield: "Equal",
      widthscustomfield: "Custom (1 - 16)",
      typefield: "Type",
      orientationcolumnsfield: "Columns",
      orientationrowsfield: "Rows"
    },
    containerform: {
      namefield: "Name",
      floatfield: "Float",
      floatnonefield: "None",
      floatleftfield: "Left",
      floatrightfield: "Right"
    },
    swzcontainerform: {
      namefield: "Name",
      openModal: "isOpen",
      displayfield: "Display",
      displaynonefield: "None",
      displayblockfield: "Block",
      displaydisplayfield: "Display",
      displayOutput: "Display",
      editorState: "Editor State",
      viewState: "View State"
    },
    imageform:{
      namefield: "Name",
      srcfield: "Source",
      hreffield: "Href",
      optionsfield: "Options",
      avatarfield: "Avatar",
      borderedfield: "Bordered",
      centeredfield: "Centered",
      disabledfield: "Disabled",
      inlinefield: "Inline",
      spacedfield: "Spaced",
      floatedfield: "Floated",
      floatedleftfield: "Left",
      floatedrightfield: "Right",
      verticalalignfield: "Vertical align",
      verticalaligntopfield: "Top",
      verticalalignmiddlefield: "Middle",
      verticalalignbottomfield: "Bottom"
    },
    statisticform: {
      namefield: "Name",
      optionsfield: "Options",
      floatedfield: "Floated",
      horizontalfield: "Horizontal",
      datafield: "Data",
      sizefield: "Size"
    },
    gridform: {
      namefield: "Name",
      optionsfield: "Options",
      multiselectfield: "Multiselect",
      filterrowfield: "Filter row",
      disablesortfield: "Disable sorting",
      editformfield: "Edit form",
      reviewformfield: "Review form",
      editformshowtypefield: "Edit form show type",
      editformtypedefaultfield: "Default",
      editformtypemodalfield: "Modal",
      columnsfield: "Columns",
      keycolumn: "Key",
      namecolumn: "Name",
      typecolumn: "Type",
      widthcolumn: "Width",
      resizablecolumn: "Resizable",
      rowkeyfield: "Row key",
      pagertypefield: "Pagination type",
      pagertypenonefield: "None",
      pagertypeserverfield: "Server",
      pagesizefield: "Page size",
      defaultsortfield: "Default sort",
      rowheightfield: "Row height",
      minheightfield: "Min height",
      autoheightfield: "Auto Height",
      offsetfield: "OffSet",
      editType: "Edit type",
      editflowfield: "Edit flow"
    },
    collectioneditorform: {
      namefield: "Name",
      idfield: "Id field",
      optionsfield: "Options",
      readonlyfield: "ReadOnly",
      draggablefield: "Draggable",
      hierarchicalfield: "Hierarchical",
      collapseallfield: "Collapse all",
      parentidfield: "ParentId field",
      columnsfield: "Columns",
      keycolumn: "Key",
      namecolumn: "Name",
      controlcolumn: "Control",
      widthcolumn: "Width",
      disableAdd: "Disable Add",
      disableDelete: "Disable Delete",
      childrenField: "Children field"
    },
    customform: {
      namefield: "Name",
      typefield: "Type control",
      propsfield: "Props",
      childrenfield: "Children",
    },
    customblockform: {
      namefield: "Name",
      sourcetypefield: "Source type",
      sourcetypeformfield: "Form name",
      sourcetypejsonfield: "JSON source",
      formnamefield: "Form name",
      sourcefield: "JSON source",
      placeholderfield: "Placeholder"
    },
    menuform: {
      namefield: "Name",
      activeitemfield: "Active Item",
      itemsfield: "Items",
      itemstargetcolumn: "Target",
      itemstitlecolumn: "Title",
      optionsfield: "Options",
      pointingfield: "Pointing",
      secondaryfield: "Secondary",
      tabularfield: "Tabular",
      fluidfield: "Fluid",
      verticalfield: "Vertical",
      linkfield: "Link",
      visibleConditioncolumn: "Visible Condition"
    },
    dropdowntriggerform:{
      namefield: "Name",
      defaultvaluefield: "Default Value",
      itemsfield: "Items",
      itemstargetcolumn: "Target",
      itemstitlecolumn: "Title",
      itemsvisibleconditioncolumn: "Visible Condition",
      imageurlfield: "ImageUrl"
    },
    chartform:{
      namefield: "Name",
      titlefield: "Title",
      titlesizefield: "Title size",
      legendpositionfield: "Legend position",
      responsivefield: "Responsive",
      datasetcustomfield: "Dataset custom",
      datalabelsplaceholder: "Q1, Q2, Q3, Q4",
      datalabelsfield: "Data labels",
      datasetlabelfield: "Dataset Label",
      datasetbackgroundcolorfield: "Dataset BackgroundColor"
    },
    workflowform:{
      namefield: "Name",
      setstatebuttonfield: "Set state button",
      blocksetstatefield: "Block SetState"
    },
    uploadform:{
      namefield: "Name",
      iconFiletypes: "Icon file types",
      customPostUrl: "Custom post url",
      showFiletypeIcon: "Show file type icon",
      autoProcessQueue: "Auto process queue",
      addRemoveLinks: "Add remove links",
      multile: "Multiple file upload"
    },
    breadcrumbform:{
      namefield: "Name",
      itemsfield: "Items",
      itemstextcolumn: "Text",
      itemsurlcolumn: "Url",
      itemsactivecolumn: "Active",
      itemsiconcolumn: "Divider Icon"
    },
    searchform:{
      namefield: "Name",
      urlfield: "Url",
      categoryfield: "Enable Categories"
    },
    rulesModal:{
      triggerbutton: "Rules...",
      title: "Validation Rules",
      validationRule: "Validation Rule",
      namecolumn: "Name",
      descriptioncolumn: "Description",
      closebutton: "Close",
      loadingtext: "Fetching rule list...",
      applybutton: "Apply",
      applyrule: "Select from library",
      comments: "Comments"
    }
  }
};

module.exports = lang;