CREATE TABLE [dbo].[QNN_SCHEDULED_EXPORT_RECIPIENT] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [DplyId]         UNIQUEIDENTIFIER NOT NULL,
    [SecurityUserId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_QNN_SCHEDULED_EXPORT_RECIPIENT] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_SCHEDULED_EXPORT_RECIPIENT_dwSecurityUser] FOREIGN KEY ([SecurityUserId]) REFERENCES [dbo].[dwSecurityUser] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_SCHEDULED_EXPORT_RECIPIENT_QNN_DPLY] FOREIGN KEY ([DplyId]) REFERENCES [dbo].[QNN_DPLY] ([Id]) ON DELETE CASCADE
);





