CREATE TABLE [dbo].[QNN_STATUS_FLOW] (
    [Id]         UNIQUEIDENTIFIER NOT NULL,
    [NumberId]   INT              IDENTITY (1, 1) NOT NULL,
    [FromStatus] UNIQUEIDENTIFIER NOT NULL,
    [ToStatus]   UNIQUEIDENTIFIER NOT NULL,
    [CreateBy]   INT              NULL,
    [CreateOn]   DATETIME         NULL,
    CONSTRAINT [PK_QNN_STATUS_FLOW] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_STATUS_FLOW_QNN_FROMSTATUS] FOREIGN KEY ([FromStatus]) REFERENCES [dbo].[QNN_STATUS] ([Id]),
    CONSTRAINT [FK_QNN_STATUS_FLOW_QNN_TOSTATUS] FOREIGN KEY ([ToStatus]) REFERENCES [dbo].[QNN_STATUS] ([Id])
);

