CREATE TABLE [dbo].[QNN_QNN_REVIEW_FILES] (
    [Id]       UNIQUEIDENTIFIER NOT NULL,
    [NumberId] INT              IDENTITY (1, 1) NOT NULL,
    [ReviewId] UNIQUEIDENTIFIER NOT NULL,
    [token]    NVARCHAR (50)    NULL,
    [Name]     NVARCHAR (256)   NULL,
    [Size]     INT              NULL,
    CONSTRAINT [PK_QNN_QNN_REVIEW_FILES] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_QNN_REVIEW_FILES_ReviewId] FOREIGN KEY ([ReviewId]) REFERENCES [dbo].[QNN_QNN_REVIEW] ([Id]) ON DELETE CASCADE
);

