CREATE TABLE [dbo].[QNN_LIST_PROP_OPT] (
    [Id]       UNIQUEIDENTIFIER NOT NULL,
    [NumberId] INT              IDENTITY (1, 1) NOT NULL,
    [PropId]   UNIQUEIDENTIFIER NOT NULL,
    [OptVal]   NVARCHAR (50)    NOT NULL,
    [OptTxt]   NVARCHAR (255)   NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_LIST_PROP_OPT_QNN_LIST_PROP] FOREIGN KEY ([PropId]) REFERENCES [dbo].[QNN_LIST_PROP] ([Id]) ON DELETE CASCADE,
    UNIQUE NONCLUSTERED ([PropId] ASC, [OptVal] ASC)
);

