CREATE TABLE [dbo].[QNN_GLOBAL_MSG_SAMPLE] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [NumberId]      INT              IDENTITY (1, 1) NOT NULL,
    [GlobalMsgId]   UNIQUEIDENTIFIER NOT NULL,
    [SampleId]      UNIQUEIDENTIFIER NOT NULL,
    [CreatedDate]   DATETIME         NOT NULL,
    [EmailSentDate] DATETIME         NULL,
    [CcEmails]      NVARCHAR (MAX)   NULL,
    [ToEmails]      NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_QNN_GLOBAL_MSG_SAMPLE] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_GLOBAL_MSG_SAMPLE_GlobalMsgId] FOREIGN KEY ([GlobalMsgId]) REFERENCES [dbo].[QNN_GLOBAL_MSG] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_GLOBAL_MSG_SAMPLE_SampleId] FOREIGN KEY ([SampleId]) REFERENCES [dbo].[QNN_SAMPLE] ([Id]) ON DELETE CASCADE
);



