CREATE TABLE [dbo].[QNN_DPLY_MSG_SAMPLE] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [NumberId]      INT              IDENTITY (1, 1) NOT NULL,
    [DplyMsgId]     UNIQUEIDENTIFIER NOT NULL,
    [ListSampleId]  UNIQUEIDENTIFIER NOT NULL,
    [CreatedDate]   DATETIME         NULL,
    [EmailSentDate] DATETIME         NULL,
    [ToEmails]      NVARCHAR (MAX)   NULL,
    [CcEmails]      NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_QNN_DPLY_MSG_SAMPLE] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_DPLY_MSG_SAMPLE_DplyMsgId] FOREIGN KEY ([DplyMsgId]) REFERENCES [dbo].[QNN_DPLY_MSG] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_DPLY_MSG_SAMPLE_ListSampleId] FOREIGN KEY ([ListSampleId]) REFERENCES [dbo].[QNN_LIST_SAMPLE] ([Id]) ON DELETE CASCADE
);




GO
CREATE NONCLUSTERED INDEX [IDX_DplyMsgId]
    ON [dbo].[QNN_DPLY_MSG_SAMPLE]([DplyMsgId] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ListSampleId]
    ON [dbo].[QNN_DPLY_MSG_SAMPLE]([ListSampleId] ASC);

