CREATE TABLE [dbo].[QNN_DPLY_STRATA_QUOTA] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [NumberId]    INT              IDENTITY (1, 1) NOT NULL,
    [DplyId]      UNIQUEIDENTIFIER NOT NULL,
    [StrataValue] NVARCHAR (255)   NULL,
    [MaxResponse] INT              NOT NULL,
    [Description] NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_QNN_DPLY_STRATA_QUOTA] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_DPLY_STRATA_QUOTA_DplyId] FOREIGN KEY ([DplyId]) REFERENCES [dbo].[QNN_DPLY] ([Id]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [UQ_QNN_DPLY_STRATA_QUOTA_DplyId_StrataValue] UNIQUE NONCLUSTERED ([DplyId] ASC, [StrataValue] ASC)
);






GO
CREATE CLUSTERED INDEX [CI_DplyId]
    ON [dbo].[QNN_DPLY_STRATA_QUOTA]([DplyId] ASC);

