CREATE TABLE [dbo].[QNN_GLOBAL_MSG_USER] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [NumberId]      INT              IDENTITY (1, 1) NOT NULL,
    [GlobalMsgId]   UNIQUEIDENTIFIER NOT NULL,
    [UserId]        UNIQUEIDENTIFIER NOT NULL,
    [CreatedDate]   DATETIME         NOT NULL,
    [EmailSentDate] DATETIME         NULL,
    CONSTRAINT [PK_QNN_GLOBAL_MSG_USER] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_GLOBAL_MSG_USER_dwSecurityUser] FOREIGN KEY ([UserId]) REFERENCES [dbo].[dwSecurityUser] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_GLOBAL_MSG_USER_GlobalMsgId] FOREIGN KEY ([GlobalMsgId]) REFERENCES [dbo].[QNN_GLOBAL_MSG] ([Id]) ON DELETE CASCADE
);

