CREATE TABLE [dbo].[QNN_LIST_SAMPLE_PROP] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [NumberId]     INT              IDENTITY (1, 1) NOT NULL,
    [ListId]       UNIQUEIDENTIFIER NOT NULL,
    [ListSampleId] UNIQUEIDENTIFIER NOT NULL,
    [ListPropId]   UNIQUEIDENTIFIER NOT NULL,
    [PropValue]    NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_LIST_SAMPLE_PROP] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_LIST_SAMPLE_PROP_QNN_LIST] FOREIGN KEY ([ListId]) REFERENCES [dbo].[QNN_LIST] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_LIST_SAMPLE_PROP_QNN_LIST_PROP] FOREIGN KEY ([ListPropId]) REFERENCES [dbo].[QNN_LIST_PROP] ([Id]),
    CONSTRAINT [FK_QNN_LIST_SAMPLE_PROP_QNN_LIST_SAMPLE] FOREIGN KEY ([ListSampleId]) REFERENCES [dbo].[QNN_LIST_SAMPLE] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ListId]
    ON [dbo].[QNN_LIST_SAMPLE_PROP]([ListId] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ListPropId]
    ON [dbo].[QNN_LIST_SAMPLE_PROP]([ListPropId] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ListSampleId]
    ON [dbo].[QNN_LIST_SAMPLE_PROP]([ListSampleId] ASC);

