CREATE TABLE [dbo].[QNN_DPLY_RECURRENCE_PREPOPULATE_FIELD] (
    [Id]         UNIQUEIDENTIFIER NOT NULL,
    [DplyId]     UNIQUEIDENTIFIER NOT NULL,
    [QnnFieldId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_QNN_DPLY_RECURRENCE_PREPOPULATE_FIELD] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_DPLY_RECURRENCE_PREPOPULATE_FIELD_QNN_DPLY_Id] FOREIGN KEY ([DplyId]) REFERENCES [dbo].[QNN_DPLY] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_DPLY_RECURRENCE_PREPOPULATE_FIELD_QNN_QNN_FIELD_Id] FOREIGN KEY ([QnnFieldId]) REFERENCES [dbo].[QNN_QNN_FIELD] ([Id])
);

