CREATE TABLE [dbo].[QNN_QNN_FORM] (
    [Id]       UNIQUEIDENTIFIER NOT NULL,
    [NumberId] INT              IDENTITY (1, 1) NOT NULL,
    [QnnId]    UNIQUEIDENTIFIER NOT NULL,
    [Name]     NVARCHAR (256)   NULL,
    [Language] NVARCHAR (50)    NULL,
    [Remarks]  NVARCHAR (300)   NULL,
    CONSTRAINT [PK__QNN_QNN___3214EC07B8F4006E] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_FORM_QNN_QNN_QnnId] FOREIGN KEY ([QnnId]) REFERENCES [dbo].[QNN_QNN] ([Id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_QnnId]
    ON [dbo].[QNN_QNN_FORM]([QnnId] ASC);

