CREATE TABLE [dbo].[QNN_DPLY_MSG_FORSTATUS] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [DplyMsgId] UNIQUEIDENTIFIER NOT NULL,
    [ForStatus] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_QNN_DPLY_MSG_FORSTATUS] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_DPLY_MSG_FORSTATUS_DplyId] FOREIGN KEY ([DplyMsgId]) REFERENCES [dbo].[QNN_DPLY_MSG] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_DPLY_MSG_FORSTATUS_ForStatus] FOREIGN KEY ([ForStatus]) REFERENCES [dbo].[QNN_STATUS] ([Id]) ON DELETE CASCADE
);

