CREATE TABLE [dbo].[QNN_LIST_SAMPLE] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [NumberId]     INT              IDENTITY (1, 1) NOT NULL,
    [ListId]       UNIQUEIDENTIFIER NOT NULL,
    [ActiveYN]     BIT              DEFAULT ((0)) NOT NULL,
    [CreatedBy]    UNIQUEIDENTIFIER NULL,
    [CreatedDate]  DATETIME         NULL,
    [UpdatedBy]    UNIQUEIDENTIFIER NULL,
    [UpdatedDate]  DATETIME         NULL,
    [IsDeleted]    BIT              DEFAULT ((0)) NOT NULL,
    [DeletedBy]    UNIQUEIDENTIFIER NULL,
    [DeletedDate]  DATETIME         NULL,
    [SampleId]     UNIQUEIDENTIFIER NOT NULL,
    [SamplePeerId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_QNN_LIST_SAMPLE] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_QNN_LIST_SAMPLE_QNN_LIST] FOREIGN KEY ([ListId]) REFERENCES [dbo].[QNN_LIST] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_LIST_SAMPLE_QNN_SAMPLE_SAMPLEID] FOREIGN KEY ([SampleId]) REFERENCES [dbo].[QNN_SAMPLE] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_LIST_SAMPLE_QNN_SAMPLE_SAMPLEPEERID] FOREIGN KEY ([SamplePeerId]) REFERENCES [dbo].[QNN_SAMPLE] ([Id]),
    CONSTRAINT [QNN_LIST_SAMPLE_UNIQUE_SAMPLE] UNIQUE NONCLUSTERED ([ListId] ASC, [SampleId] ASC, [SamplePeerId] ASC) WITH (FILLFACTOR = 80)
);






GO
CREATE NONCLUSTERED INDEX [IDX_ListId]
    ON [dbo].[QNN_LIST_SAMPLE]([ListId] ASC) WITH (FILLFACTOR = 80);




GO
CREATE NONCLUSTERED INDEX [IDX_SampleId]
    ON [dbo].[QNN_LIST_SAMPLE]([SampleId] ASC) WITH (FILLFACTOR = 80);




GO
CREATE NONCLUSTERED INDEX [IDX_SamplePeerId]
    ON [dbo].[QNN_LIST_SAMPLE]([SamplePeerId] ASC) WITH (FILLFACTOR = 80);




GO
CREATE NONCLUSTERED INDEX [IDX_Id_includes]
    ON [dbo].[QNN_LIST_SAMPLE]([Id] ASC)
    INCLUDE([SampleId], [SamplePeerId], [ListId], [ActiveYN]) WITH (FILLFACTOR = 80);

