CREATE TABLE [dbo].[QNN_SAMPLE_REMARKS] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [SampleId]         UNIQUEIDENTIFIER NOT NULL,
    [StructDivisionId] UNIQUEIDENTIFIER NOT NULL,
    [Remarks]          NVARCHAR (1024)  CONSTRAINT [DF_QNN_SAMPLE_REMARKS_Remarks] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_QNN_SAMPLE_REMARKS] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_QNN_SAMPLE_REMARKS_QNN_SAMPLE] FOREIGN KEY ([SampleId]) REFERENCES [dbo].[QNN_SAMPLE] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_SAMPLE_REMARKS_StructDivision] FOREIGN KEY ([StructDivisionId]) REFERENCES [dbo].[StructDivision] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [UQ_QNN_SAMPLE_REMARKS_SampleId_StructDivisionId] UNIQUE NONCLUSTERED ([SampleId] ASC, [StructDivisionId] ASC) WITH (FILLFACTOR = 80)
);

