CREATE TABLE [dbo].[QNN_DPLY_SAMPLE_OWNER] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [NumberId]     INT              IDENTITY (1, 1) NOT NULL,
    [DplyId]       UNIQUEIDENTIFIER NOT NULL,
    [ListSampleId] UNIQUEIDENTIFIER NULL,
    [UserId]       UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_QNN_DPLY_SAMPLE_OWNER] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_QNN_DPLY_SAMPLE_OWNER_DplyId] FOREIGN KEY ([DplyId]) REFERENCES [dbo].[QNN_DPLY] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_DPLY_SAMPLE_OWNER_ListSampleId] FOREIGN KEY ([ListSampleId]) REFERENCES [dbo].[QNN_LIST_SAMPLE] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_DPLY_SAMPLE_OWNER_UserId_dwSecurity_Id] FOREIGN KEY ([UserId]) REFERENCES [dbo].[dwSecurityUser] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [UQ_DPLY_SAMPLE_OWNER] UNIQUE NONCLUSTERED ([DplyId] ASC, [UserId] ASC, [ListSampleId] ASC) WITH (FILLFACTOR = 80)
);




GO



GO
CREATE NONCLUSTERED INDEX [IDX_ListSampleId]
    ON [dbo].[QNN_DPLY_SAMPLE_OWNER]([ListSampleId] ASC) WITH (FILLFACTOR = 80);




GO
CREATE NONCLUSTERED INDEX [IDX_UserId]
    ON [dbo].[QNN_DPLY_SAMPLE_OWNER]([UserId] ASC) WITH (FILLFACTOR = 80);



