CREATE TABLE [dbo].[QNN_LIST_REVIEW_FILES] (
    [Id]       UNIQUEIDENTIFIER NOT NULL,
    [NumberId] INT              IDENTITY (1, 1) NOT NULL,
    [ReviewId] UNIQUEIDENTIFIER NOT NULL,
    [token]    NVARCHAR (50)    NULL,
    [Name]     NVARCHAR (256)   NULL,
    [Size]     INT              NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_LIST_REVIEW_FILES_QNN_LIST_REVIEW] FOREIGN KEY ([ReviewId]) REFERENCES [dbo].[QNN_LIST_REVIEW] ([Id]) ON DELETE CASCADE
);

