CREATE TABLE [dbo].[QNN_DPLY_SAMPLE_DUEDATE] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [NumberId]     INT              IDENTITY (1, 1) NOT NULL,
    [DplyId]       UNIQUEIDENTIFIER NOT NULL,
    [ListSampleId] UNIQUEIDENTIFIER NOT NULL,
    [DueDate]      DATETIME         NOT NULL,
    CONSTRAINT [PK_QNN_DPLY_SAMPLE_DUEDATE] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_DPLY_SAMPLE_DUEDATE_DplyId] FOREIGN KEY ([DplyId]) REFERENCES [dbo].[QNN_DPLY] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_DPLY_SAMPLE_DUEDATE_ListSampleId] FOREIGN KEY ([ListSampleId]) REFERENCES [dbo].[QNN_LIST_SAMPLE] ([Id]) ON DELETE CASCADE
);




GO
CREATE NONCLUSTERED INDEX [IDX_DplyId]
    ON [dbo].[QNN_DPLY_SAMPLE_DUEDATE]([DplyId] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ListSampleId_includes]
    ON [dbo].[QNN_DPLY_SAMPLE_DUEDATE]([ListSampleId] ASC)
    INCLUDE([DplyId], [DueDate]);

