CREATE TABLE [dbo].[QNN_REPORT_SNAPSHOT] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [BatchNo]     NVARCHAR (50)    NOT NULL,
    [NumberId]    INT              IDENTITY (1, 1) NOT NULL,
    [DplyId]      UNIQUEIDENTIFIER NOT NULL,
    [Status]      UNIQUEIDENTIFIER NOT NULL,
    [Weightgroup] NVARCHAR (25)    NOT NULL,
    [Count]       INT              NOT NULL,
    [CreatedDate] DATETIME         NOT NULL,
    CONSTRAINT [PK_QNN_REPORT_SNAPSHOT] PRIMARY KEY NONCLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_QNN_REPORT_SNAPSHOT_DplyId] FOREIGN KEY ([DplyId]) REFERENCES [dbo].[QNN_DPLY] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [UQ_NumberId] UNIQUE NONCLUSTERED ([NumberId] ASC) WITH (FILLFACTOR = 100)
);




GO
CREATE NONCLUSTERED INDEX [IDX_DplyId]
    ON [dbo].[QNN_REPORT_SNAPSHOT]([DplyId] ASC)
    INCLUDE([BatchNo], [CreatedDate]) WITH (FILLFACTOR = 100);


GO
CREATE CLUSTERED INDEX [CI_BatchNo]
    ON [dbo].[QNN_REPORT_SNAPSHOT]([BatchNo] ASC) WITH (FILLFACTOR = 100);

