CREATE TABLE [dbo].[QNN_SAMPLE_STRUCTDIVISION] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [SampleId]         UNIQUEIDENTIFIER NOT NULL,
    [StructDivisionId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_QNN_SAMPLE_STRUCTDIVISION] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_SAMPLE_STRUCTDIVISION_QNN_SAMPLE] FOREIGN KEY ([SampleId]) REFERENCES [dbo].[QNN_SAMPLE] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_SAMPLE_STRUCTDIVISION_StructDivsion] FOREIGN KEY ([StructDivisionId]) REFERENCES [dbo].[StructDivision] ([Id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_SampleId]
    ON [dbo].[QNN_SAMPLE_STRUCTDIVISION]([SampleId] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_StructDivisionId]
    ON [dbo].[QNN_SAMPLE_STRUCTDIVISION]([StructDivisionId] ASC);

