CREATE TABLE [dbo].[QNN_GLOBAL_MSG_FORSTATUS] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [GlobalMsgId] UNIQUEIDENTIFIER NOT NULL,
    [ForStatus]   UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_QNN_GLOBAL_MSG_FORSTATUS] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QNN_GLOBAL_MSG_FORSTATUS_ForStatus] FOREIGN KEY ([ForStatus]) REFERENCES [dbo].[QNN_STATUS] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_GLOBAL_MSG_FORSTATUS_GlobalMsgId] FOREIGN KEY ([GlobalMsgId]) REFERENCES [dbo].[QNN_GLOBAL_MSG] ([Id]) ON DELETE CASCADE
);

