CREATE TABLE [dbo].[QNN_RESP_ANS] (
    [Id]             UNIQUEIDENTIFIER CONSTRAINT [DF_QNN_RESP_ANS_Id] DEFAULT (newsequentialid()) NOT NULL,
    [NumberId]       INT              IDENTITY (1, 1) NOT NULL,
    [RespId]         UNIQUEIDENTIFIER NOT NULL,
    [QnnFieldId]     UNIQUEIDENTIFIER NOT NULL,
    [AnsVal]         NVARCHAR (MAX)   NULL,
    [IsPrePopulated] BIT              CONSTRAINT [DF_QNN_RESP_ANS_IsPrePopulated] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_QNN_RESP_ANS] PRIMARY KEY NONCLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_QNN_RESP_ANS_QnnFieldId] FOREIGN KEY ([QnnFieldId]) REFERENCES [dbo].[QNN_QNN_FIELD] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_QNN_RESP_ANS_RespId] FOREIGN KEY ([RespId]) REFERENCES [dbo].[QNN_RESP] ([Id]) ON DELETE CASCADE
);





GO
ALTER TABLE [dbo].[QNN_RESP_ANS] SET (LOCK_ESCALATION = DISABLE);







GO





GO
CREATE NONCLUSTERED INDEX [IDX_QnnFieldId]
    ON [dbo].[QNN_RESP_ANS]([QnnFieldId] ASC) WITH (FILLFACTOR = 80);




GO
CREATE CLUSTERED INDEX [CI_RespId]
    ON [dbo].[QNN_RESP_ANS]([RespId] ASC) WITH (FILLFACTOR = 80);

